### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by joshgojer** [sonburn/symbol-instance-locator#23]
It works with some files and not others. All my files are created the same way. So I don't understand why it works on some and not others. There is a discrepancy between versions of the same file. Older versions work and newer ones don't. Any advice will be very helpful. Seems like something broke between versions. Nothing has changed except the deletion of excess symbols.

**Comment by sonburn** [comment]
@joshgojer I'm not experiencing any failures in the various documents I work in. Are you able to check the logs to find out what error is being presented, if one is occurring?

1. Open Utilities > Console.app
2. Type the word "sketch" in the search bar, and hit enter. This will convert the key word to a pill, with a dropdown. Change the dropdown to "Library".
3. If existing log data is presented, you can start fresh by clicking the "Clear" action (this doesn't delete anything)
4. Run the plugin in Sketch, and if there was an error it should appear in Console.app
5. Copy/paste the output here

**Comment by bchucherko** [comment]
@sonburn for me the same problem - stopped working in Sketch65.

console output:

```Error: An Obj-C exception occurred.
    at [native code] (/)
    at /Users/xxx/Library/Application Support/com.bohemiancoding.sketch3/Plugins/symbol-instance-locator-master/Symbol Instance Locator.sketchplugin/Contents/Sketch/script.js:402:46
    at forEach[native code] (/)
    at getSymbolOverrides (/Users/xxx/Library/Application Support/com.bohemiancoding.sketch3/Plugins/symbol-instance-locator-master/Symbol Instance Locator.sketchplugin/Contents/Sketch/script.js:399:37)
    at locate (/Users/xxx/Library/Application Support/com.bohemiancoding.sketch3/Plugins/symbol-instance-locator-master/Symbol Instance Locator.sketchplugin/Contents/Sketch/script.js:32:42)
  nativeException: -[MSImmutableColor setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x600011e7cfc0```

**Comment by rekker** [comment]
Hi @sonburn,

For me, the plugin also works on some documents and not on others, this is my error log of the document where it doesn't load:

```
Error: An Obj-C exception occurred.
    at [native code] (/)
    at /Users/../Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Locator.sketchplugin/Contents/Sketch/script.js:402:46
    at forEach[native code] (/)
    at getSymbolOverrides (/Users/../Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Locator.sketchplugin/Contents/Sketch/script.js:399:37)
    at locate (/Users/../Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Locator.sketchplugin/Contents/Sketch/script.js:32:42)
  nativeException: -[MSImmutableColor setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x60002dd382d0
```
